packages:
  - .

allowBuilds:
  workerd: true
  "@mongodb-js/zstd": false
  "@parcel/watcher": false
  core-js-pure: false
  esbuild: false
  msgpackr-extract: false
  msw: false
  node-liblzma: false

minimumReleaseAge: 0
