# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

application_url = "https://shopify.dev/apps/default-app-home"
embedded = true
name = "baton-local"
handle = "baton-local"
client_id = ""

[webhooks]
api_version = "2026-10"

[[webhooks.subscriptions]]
uri = "/webhooks/compliance"
compliance_topics = [
  "customers/data_request",
  "customers/redact",
  "shop/redact",
]

[[webhooks.subscriptions]]
uri = "/webhooks/app/scopes_update"
topics = ["app/scopes_update"]

[[webhooks.subscriptions]]
uri = "/webhooks/app/uninstalled"
topics = ["app/uninstalled"]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = ["https://shopify.dev/apps/default-app-home/api/auth"]

[build]
automatically_update_urls_on_dev = true
