# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "7c6cceb7f8f9991a543d43648b08e72d"
application_url = "https://example.com"
embedded = true
name = "baton-local"
handle = "baton-local"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = ["https://example.com/api/auth"]

[webhooks]
api_version = "2026-10"

[[webhooks.subscriptions]]
uri = "/webhooks/compliance"
compliance_topics = [
  "customers/data_request",
  "customers/redact",
  "shop/redact",
]

[[webhooks.subscriptions]]
uri = "/webhooks/app/scopes_update"
topics = ["app/scopes_update"]

[[webhooks.subscriptions]]
uri = "/webhooks/app/uninstalled"
topics = ["app/uninstalled"]
[build]
automatically_update_urls_on_dev = true
