/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AppRouteImport } from './routes/app'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminLogoutRouteImport } from './routes/admin.logout'
import { Route as AdminOrphanShopAgentObjectsRouteImport } from './routes/admin.orphan-shop-agent-objects'
import { Route as AdminShopAgentObjectsRouteImport } from './routes/admin.shop-agent-objects'
import { Route as AdminShopsRouteImport } from './routes/admin.shops'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppMembersRouteImport } from './routes/app.members'
import { Route as AuthSplatRouteImport } from './routes/auth.$'
import { Route as WebhooksComplianceRouteImport } from './routes/webhooks.compliance'
import { Route as AdminShopShopRouteImport } from './routes/admin.shop.$shop'
import { Route as WebhooksAppScopes_updateRouteImport } from './routes/webhooks.app.scopes_update'
import { Route as WebhooksAppUninstalledRouteImport } from './routes/webhooks.app.uninstalled'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLogoutRoute = AdminLogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrphanShopAgentObjectsRoute =
  AdminOrphanShopAgentObjectsRouteImport.update({
    id: '/orphan-shop-agent-objects',
    path: '/orphan-shop-agent-objects',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminShopAgentObjectsRoute = AdminShopAgentObjectsRouteImport.update({
  id: '/shop-agent-objects',
  path: '/shop-agent-objects',
  getParentRoute: () => AdminRoute,
} as any)
const AdminShopsRoute = AdminShopsRouteImport.update({
  id: '/shops',
  path: '/shops',
  getParentRoute: () => AdminRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppMembersRoute = AppMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AppRoute,
} as any)
const AuthSplatRoute = AuthSplatRouteImport.update({
  id: '/auth/$',
  path: '/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const WebhooksComplianceRoute = WebhooksComplianceRouteImport.update({
  id: '/webhooks/compliance',
  path: '/webhooks/compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminShopShopRoute = AdminShopShopRouteImport.update({
  id: '/shop/$shop',
  path: '/shop/$shop',
  getParentRoute: () => AdminRoute,
} as any)
const WebhooksAppScopes_updateRoute =
  WebhooksAppScopes_updateRouteImport.update({
    id: '/webhooks/app/scopes_update',
    path: '/webhooks/app/scopes_update',
    getParentRoute: () => rootRouteImport,
  } as any)
const WebhooksAppUninstalledRoute = WebhooksAppUninstalledRouteImport.update({
  id: '/webhooks/app/uninstalled',
  path: '/webhooks/app/uninstalled',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/logout': typeof AdminLogoutRoute
  '/admin/orphan-shop-agent-objects': typeof AdminOrphanShopAgentObjectsRoute
  '/admin/shop-agent-objects': typeof AdminShopAgentObjectsRoute
  '/admin/shops': typeof AdminShopsRoute
  '/app/members': typeof AppMembersRoute
  '/auth/$': typeof AuthSplatRoute
  '/webhooks/compliance': typeof WebhooksComplianceRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/admin/shop/$shop': typeof AdminShopShopRoute
  '/webhooks/app/scopes_update': typeof WebhooksAppScopes_updateRoute
  '/webhooks/app/uninstalled': typeof WebhooksAppUninstalledRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/logout': typeof AdminLogoutRoute
  '/admin/orphan-shop-agent-objects': typeof AdminOrphanShopAgentObjectsRoute
  '/admin/shop-agent-objects': typeof AdminShopAgentObjectsRoute
  '/admin/shops': typeof AdminShopsRoute
  '/app/members': typeof AppMembersRoute
  '/auth/$': typeof AuthSplatRoute
  '/webhooks/compliance': typeof WebhooksComplianceRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
  '/admin/shop/$shop': typeof AdminShopShopRoute
  '/webhooks/app/scopes_update': typeof WebhooksAppScopes_updateRoute
  '/webhooks/app/uninstalled': typeof WebhooksAppUninstalledRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/logout': typeof AdminLogoutRoute
  '/admin/orphan-shop-agent-objects': typeof AdminOrphanShopAgentObjectsRoute
  '/admin/shop-agent-objects': typeof AdminShopAgentObjectsRoute
  '/admin/shops': typeof AdminShopsRoute
  '/app/members': typeof AppMembersRoute
  '/auth/$': typeof AuthSplatRoute
  '/webhooks/compliance': typeof WebhooksComplianceRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/admin/shop/$shop': typeof AdminShopShopRoute
  '/webhooks/app/scopes_update': typeof WebhooksAppScopes_updateRoute
  '/webhooks/app/uninstalled': typeof WebhooksAppUninstalledRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/privacy'
    | '/admin/login'
    | '/admin/logout'
    | '/admin/orphan-shop-agent-objects'
    | '/admin/shop-agent-objects'
    | '/admin/shops'
    | '/app/members'
    | '/auth/$'
    | '/webhooks/compliance'
    | '/admin/'
    | '/app/'
    | '/admin/shop/$shop'
    | '/webhooks/app/scopes_update'
    | '/webhooks/app/uninstalled'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/privacy'
    | '/admin/login'
    | '/admin/logout'
    | '/admin/orphan-shop-agent-objects'
    | '/admin/shop-agent-objects'
    | '/admin/shops'
    | '/app/members'
    | '/auth/$'
    | '/webhooks/compliance'
    | '/admin'
    | '/app'
    | '/admin/shop/$shop'
    | '/webhooks/app/scopes_update'
    | '/webhooks/app/uninstalled'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/privacy'
    | '/admin/login'
    | '/admin/logout'
    | '/admin/orphan-shop-agent-objects'
    | '/admin/shop-agent-objects'
    | '/admin/shops'
    | '/app/members'
    | '/auth/$'
    | '/webhooks/compliance'
    | '/admin/'
    | '/app/'
    | '/admin/shop/$shop'
    | '/webhooks/app/scopes_update'
    | '/webhooks/app/uninstalled'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  AuthSplatRoute: typeof AuthSplatRoute
  WebhooksComplianceRoute: typeof WebhooksComplianceRoute
  WebhooksAppScopes_updateRoute: typeof WebhooksAppScopes_updateRoute
  WebhooksAppUninstalledRoute: typeof WebhooksAppUninstalledRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/logout': {
      id: '/admin/logout'
      path: '/logout'
      fullPath: '/admin/logout'
      preLoaderRoute: typeof AdminLogoutRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orphan-shop-agent-objects': {
      id: '/admin/orphan-shop-agent-objects'
      path: '/orphan-shop-agent-objects'
      fullPath: '/admin/orphan-shop-agent-objects'
      preLoaderRoute: typeof AdminOrphanShopAgentObjectsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/shop-agent-objects': {
      id: '/admin/shop-agent-objects'
      path: '/shop-agent-objects'
      fullPath: '/admin/shop-agent-objects'
      preLoaderRoute: typeof AdminShopAgentObjectsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/shops': {
      id: '/admin/shops'
      path: '/shops'
      fullPath: '/admin/shops'
      preLoaderRoute: typeof AdminShopsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/members': {
      id: '/app/members'
      path: '/members'
      fullPath: '/app/members'
      preLoaderRoute: typeof AppMembersRouteImport
      parentRoute: typeof AppRoute
    }
    '/auth/$': {
      id: '/auth/$'
      path: '/auth/$'
      fullPath: '/auth/$'
      preLoaderRoute: typeof AuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/webhooks/compliance': {
      id: '/webhooks/compliance'
      path: '/webhooks/compliance'
      fullPath: '/webhooks/compliance'
      preLoaderRoute: typeof WebhooksComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/shop/$shop': {
      id: '/admin/shop/$shop'
      path: '/shop/$shop'
      fullPath: '/admin/shop/$shop'
      preLoaderRoute: typeof AdminShopShopRouteImport
      parentRoute: typeof AdminRoute
    }
    '/webhooks/app/scopes_update': {
      id: '/webhooks/app/scopes_update'
      path: '/webhooks/app/scopes_update'
      fullPath: '/webhooks/app/scopes_update'
      preLoaderRoute: typeof WebhooksAppScopes_updateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/webhooks/app/uninstalled': {
      id: '/webhooks/app/uninstalled'
      path: '/webhooks/app/uninstalled'
      fullPath: '/webhooks/app/uninstalled'
      preLoaderRoute: typeof WebhooksAppUninstalledRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminLoginRoute: typeof AdminLoginRoute
  AdminLogoutRoute: typeof AdminLogoutRoute
  AdminOrphanShopAgentObjectsRoute: typeof AdminOrphanShopAgentObjectsRoute
  AdminShopAgentObjectsRoute: typeof AdminShopAgentObjectsRoute
  AdminShopsRoute: typeof AdminShopsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminShopShopRoute: typeof AdminShopShopRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminLoginRoute: AdminLoginRoute,
  AdminLogoutRoute: AdminLogoutRoute,
  AdminOrphanShopAgentObjectsRoute: AdminOrphanShopAgentObjectsRoute,
  AdminShopAgentObjectsRoute: AdminShopAgentObjectsRoute,
  AdminShopsRoute: AdminShopsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminShopShopRoute: AdminShopShopRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppRouteChildren {
  AppMembersRoute: typeof AppMembersRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppMembersRoute: AppMembersRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  AuthSplatRoute: AuthSplatRoute,
  WebhooksComplianceRoute: WebhooksComplianceRoute,
  WebhooksAppScopes_updateRoute: WebhooksAppScopes_updateRoute,
  WebhooksAppUninstalledRoute: WebhooksAppUninstalledRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
